// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0QSkIPbLkA6yvV1FR9gQU3UUE5Bq3LdA',
    appId: '1:1034898599792:web:14c3ac29084fbc28b229b5',
    messagingSenderId: '1034898599792',
    projectId: 'mypocket-4625d',
    authDomain: 'mypocket-4625d.firebaseapp.com',
    storageBucket: 'mypocket-4625d.firebasestorage.app',
    measurementId: 'G-F8ZKQKFN78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApMv0SSTrnA0rJ-NevJM_qMMNRn62VLSM',
    appId: '1:1034898599792:android:7cca26be027882bab229b5',
    messagingSenderId: '1034898599792',
    projectId: 'mypocket-4625d',
    storageBucket: 'mypocket-4625d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAssDK0cSRP1Urfi174y8suNjSJZ3LkVjI',
    appId: '1:1034898599792:ios:d66005df176afa68b229b5',
    messagingSenderId: '1034898599792',
    projectId: 'mypocket-4625d',
    storageBucket: 'mypocket-4625d.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAssDK0cSRP1Urfi174y8suNjSJZ3LkVjI',
    appId: '1:1034898599792:ios:d66005df176afa68b229b5',
    messagingSenderId: '1034898599792',
    projectId: 'mypocket-4625d',
    storageBucket: 'mypocket-4625d.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0QSkIPbLkA6yvV1FR9gQU3UUE5Bq3LdA',
    appId: '1:1034898599792:web:48fd639534f07106b229b5',
    messagingSenderId: '1034898599792',
    projectId: 'mypocket-4625d',
    authDomain: 'mypocket-4625d.firebaseapp.com',
    storageBucket: 'mypocket-4625d.firebasestorage.app',
    measurementId: 'G-2YZ3Q1M8L2',
  );
}
